version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - "8081:80"
    volumes:
      - ./files:/srv
    labels:
      - "mini-cloud.tool.name=FileBrowser"
      - "mini-cloud.tool.description=Web-based file manager"
      - "mini-cloud.tool.category=Productivity"
      - "mini-cloud.tool.port=8081"
