version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    labels:
      - "mini-cloud.tool.name=Grafana"
      - "mini-cloud.tool.description=Metrics and dashboarding"
      - "mini-cloud.tool.category=Monitoring & Analytics"
      - "mini-cloud.tool.port=3001"
