version: '3'
services:
  nocodb:
    image: nocodb/nocodb
    container_name: nocodb
    ports:
      - "8082:8080"
    labels:
      - "mini-cloud.tool.name=NocoDB"
      - "mini-cloud.tool.description=Open-source Airtable alternative"
      - "mini-cloud.tool.category=Productivity"
      - "mini-cloud.tool.port=8082"
