version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "5050:80"
    labels:
      - "mini-cloud.tool.name=pgAdmin"
      - "mini-cloud.tool.description=PostgreSQL admin GUI"
      - "mini-cloud.tool.category=Databases"
      - "mini-cloud.tool.port=5050"
