version: '3'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "mini-cloud.tool.name=Portainer"
      - "mini-cloud.tool.description=Docker GUI manager"
      - "mini-cloud.tool.category=Databases"
      - "mini-cloud.tool.port=9000"
volumes:
  portainer_data:
