version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    labels:
      - "mini-cloud.tool.name=Prometheus"
      - "mini-cloud.tool.description=Monitoring system"
      - "mini-cloud.tool.category=Monitoring & Analytics"
      - "mini-cloud.tool.port=9090"
